### PR TITLE
Use yield in contents() for lower memory usage.

### PR DESCRIPTION
**Pull request by jgmdev**

### CODE REVIEW

**Comment by splitbrain** [comment]
Tests are failing now. Can you have a look please?

**Comment by tm1000** [comment]
The issue with this PR is with the test case for counting

https://github.com/splitbrain/php-archive/blob/master/tests/TarTestCase.php#L168

EG now that it's a generator you can't count the values.
> You should understand, that generator isn't data structure - it's an instance of Generator class and, actually, it's special sort of Iterator. Thus, you can't count its items directly (to be precise - that's because Generator class implements only Iterator interface, and not Countable interface. To be honest, I can't imagine how can it implement that)

https://stackoverflow.com/questions/21604654/php-how-to-count-a-generators-yields

You also technically can't foreach over the values for the same reasons

> The problem is that the foreach try to reset (rewind) the Generator. But rewind() throws an exception if the generator is currently after the first yield.
>
> So you should avoid the foreach and use a while instead

https://stackoverflow.com/questions/33425851/php-generator-yield-the-first-value-then-iterate

The proposal here should be that a new function should be created (and tested) something called `yieldContents()` while leaving `contents()` in place.

**Comment by jgmdev** [comment]
Wow, I totally forgot about this. I guess the proposal to add a yieldContents() is better than what done on this pull request for compatibility reasons...

**Edit**: Just pushed another small change to keep backward compatibility and give access to a yieldContents() method that now serves as base for contents().

**Comment by tm1000** [comment]
Awesome @jgmdev! It passes! 

Also I should have stated that for each is actually fine. It’s only an Issue if you for each over a generator that’s already in the middle or at the end. Code looks good!

**Comment by xrobau** [comment]
Almost two years later, I discover that @tm1000 already beat me here, and ran the tests! I can confirm that THIS branch fails exactly the same tests as the current branch:

```

1) splitbrain\PHPArchive\TarTestCase::testExtractWithInvalidOutDir
Failed asserting that exception of type "splitbrain\PHPArchive\ArchiveIOException" is thrown.

2) splitbrain\PHPArchive\TarTestCase::testCreateWithInvalidFile
Failed asserting that exception of type "splitbrain\PHPArchive\ArchiveIOException" is thrown.

```
So I'm going to mark this as reviewed, and +1 for merging!

**Review by xrobau — APPROVED** [review]
Approved by me, recommended for merging.

**Comment by splitbrain** [comment]
Sorry this took so long. :pray:

**Pull request merged**
